Sprint 04
ZinovevSasha/MovieQuiz-ios pull request #2
Opened 2022-10-20 09:52 UTC by ZinovevSasha

2022-10-20 16:45 UTC, mmbabaev requested changes

2022-10-20 16:45 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                                    NSAttributedString.Key.paragraphStyle: paragraphStyle
Нужен ли нам `attributedString`, если мы используем `font`?

2022-10-20 16:45 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.titleLabel?.font =  UIFont(name: "YSDisplay-Medium", size: 20)
font-ы можно вынести в enum констант

2022-10-20 16:45 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            .reduce(0) { (i, j) in
круто, что функциональным стилем умеете. Предлагаю только не называть переменные i и j, лучше уж тогда использовать дефолтные $0. 

Вообще это вроде сокращается до `.reduce(0, +)`

2022-10-20 16:45 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
Если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-10-21 08:39 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            .reduce(0) { (i, j) in
.reduce(0, +) - гораздо лучше выглядит))

2022-10-21 08:55 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private let viewForQuestionLabel: UIView = {
Не понимаю что не так? в уроке тоже используется вью чтобы задать констрейны лейблу)

2022-10-21 09:16 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private let viewForQuestionLabel: UIView = {
Я вам предлагаю поменять строчки 70-74 на строчку из моего комментария

2022-10-21 09:17 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                                    NSAttributedString.Key.paragraphStyle: paragraphStyle
По-моему это включено в font, можете проверить, убрав attributes

2022-10-21 09:38 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.titleLabel?.font =  UIFont(name: "YSDisplay-Medium", size: 20)
Сделать экстеншн к стригу?
questionTopLabe.font = UIFont(name: .MyFonts.YSDisplayMedium.rawValue, size: 20)
Вот так или как то по другому?

2022-10-21 09:54 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.titleLabel?.font =  UIFont(name: "YSDisplay-Medium", size: 20)
```
extension UIFont {
   static let ysMedium = UIFont(name: "YSDisplay-Medium", size: 20)
}

label.font = .ysMedium
```

2022-10-21 10:35 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private let viewForQuestionLabel: UIView = {
а кажись понял) типо зачем делать клоужер если он пустой =) логично )Спасибо!

2022-10-21 11:16 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.titleLabel?.font =  UIFont(name: "YSDisplay-Medium", size: 20)
extension UIFont {
   
    static func ysDisplayBold(size: CGFloat) -> UIFont {
      guard let customFont = UIFont(name: "YSDisplay-Bold", size: size) else {
        return UIFont.systemFont(ofSize: size)
      }
      return customFont
    }
что думаете о таком варианте? тут конечно награмождено) Но зато можно установить свой размер который нужно а он у нас в приложении есть 23 в одном месте) единственное что смущает что это дом функция в которой есть Инициализатор) Не сделает ли это к тормозам если такой подход использовать?

2022-10-21 11:35 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.titleLabel?.font =  UIFont(name: "YSDisplay-Medium", size: 20)
Хорошо

2022-10-21 16:34 UTC, mmbabaev approved these changes

2022-10-21 16:34 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    lazy private var noButton: UIButton = {
на будущее: код обеих кнопок почти одинаковый, можно сделать функцию/сабкласс для переиспользования

2022-10-21 16:34 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          let yeButton = UIButton(type: .system)
опечатка

2022-10-21 18:02 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    lazy private var noButton: UIButton = {
это функция которая будет делать кнопки похожие друг на друга?

2022-10-21 18:05 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          let yeButton = UIButton(type: .system)
Мой код так первый раз проверяют. Грамматика действительно так важна и законченные названия переменных и так далее ?

2022-10-21 18:18 UTC, ZinovevSasha commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    lazy private var noButton: UIButton = {
можете пример показать что то я не понимаю) А очень хочется

2022-10-22 20:04 UTC, merged